script:
- echo "skipping tests"
deploy:
  provider: azure_storage
  edge:
    branch: sf-port-970
  on:
    all_branches: true
  account: satodpltesting
  access-key: $KEY
  local-dir: 'BUILD'
  dot_match: true
