script:
    - /bin/true

deploy:
  provider: azure_storage
  edge:
    source: sato-s/dpl
    branch: azure_storage
  on:
    all_branches: true
  account-name: satosampleapp4
  account-key: $KEY
  local-dir: 'BUILD'
  dot_match: true
