script:
    - /bin/true

deploy:
  provider: azure_storage
  edge:
    branch: master
  on:
    all_branches: true
  account-name: satodpltesting
  account-key: $KEY
  local-dir: 'BUILD'
  dot_match: true
